### ISSUE TITLE
Verifier, noexcept and exceptions

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#10]
I believe that either the `Verifier` concept used in `constrained_type` is underspecified or the latter's functions conditionally marked `noexcept` on `is_nothrow_*` are incorrect. This is because there's no restriction on `Verifier::verify()` to not throw an exception. If that happens in the mentioned functions, `std::terminate` would be called, which is probably undesirable.

**Comment by foonathan** [comment]
You are correct, I wrote the noexcept out of habit.

Would you mind doing a PR? I'm currently busy with something else.

**Comment by johelegp** [comment]
No problem! To be clear, is your desired resolution removing the `noexcept`s?

**Comment by foonathan** [comment]
I'd suggest making the private verify() function conditionally `noexcept` and then adding this constraint to the move constructor `noexcept`. So make it conditionally `noexcept` based on `verify()`. (Because I want nothrow move constructors as often as possible).

`debug_verify()` is intentionally `noexcept`, so everywhere where it is called can be left `noexcept`.

**Comment by foonathan** [comment]
Oh, and another thing: Feel free to add an acknowledgements section at the bottom of the readme like done in standardese: https://github.com/foonathan/standardese/blob/master/README.md#acknowledgements :)

**Comment by johelegp** [comment]
> Oh, and another thing: Feel free to add an acknowledgements section at the bottom of the readme like done in standardese: https://github.com/foonathan/standardese/blob/master/README.md#acknowledgements :)
I'll leave that to you ;)
