### ISSUE TITLE
Overly restrictive conversion between integer instantiations

### ISSUE THREAD

**Issue by johnmcfarlane** [foonathan/type_safe#54]
Hi Jonathan!

Looking at your documentation for *type_safe* and saw this about [`integer`](http://foonathan.net/doc/type_safe/doc_integer.html#ts::integer-IntegerT,Policy-):

> A conversion is considered safe if both integer types have the same signedness and the size of the value being converted is less than or equal to the destination size.

But what if you are converting, say, from `uint16_t` to `int32_t`?  Is this not allowed?  Is it not safe?

BTW, I have a [similar test](https://github.com/johnmcfarlane/cnl/blob/305801a35a5ca01e9983e93dec270f83321d280e/include/cnl/num_traits.h#L272) with no such restriction.

Cheers,
John

**Comment by foonathan** [comment]
I could safely allow that, but I don't really see a great use.

**Comment by nicola-gigante** [comment]
I'm also hitting with such disallowed conversions. If the library goal is to protect the programmer from mistakes, then *all* certainly safe conversions should be allowed. See it like a false positive. Too much false positives are noise and impair the use of the library. If I know for sure that safe conversions are allowed and unsafe ones are disallowed, I can reason about the code. Also, this means that compiler errors arising from switching from not using typedefs to using them would only highlight potential bugs. 

IMHO, provably safe conversions should be allowed.

**Comment by damu** [comment]
It depends on what you want to be safe against. If you only want to be safe against "unsafe" conversions then your suggestion could be considered "ok". But if you also want to be safe against accidental conversions then foonathan is "right".
Take this as an example:
```
uint16_t a=5;
uint16_t b=10;
auto c=b-a;
```
Which type and which value has c?
It is int and -5. That can be quite a bug and is pretty ridiculous. Sure a conversion from uint16_t to int32_t (or int64_t) is "safe", but is it intended/expected/correct?

**Comment by johnmcfarlane** [comment]
Well, food for thought.  BTW, I'd be fascinated to know what you think the correct result of `5-10` is if it isn't `-5`.

**Comment by damu** [comment]
Both input integers are unsigned. -5 is not unsigned. I would not expect two unsigned shorts resulting in a signed int with a negative value. That rule is called integer promotion and is kinda surprising.

**Comment by johnmcfarlane** [comment]
Well firstly, I'd argue that your degree of surprise is related to your understanding of C++.  I would expect a C++ novice to agree that `5-10 == -5`.  In fact, any other answer would be surprising to almost everyone with a basic grasp of mathematics and `65530` would not even be in the top three guesses!

Secondly, `type_safe::integer` [does not allow](http://foonathan.net/doc/type_safe/doc_integer.html#ts::integer-IntegerT,Policy-) overflow:

> It also checks against unsigned under/overflow in debug mode and marks it as undefined for the optimizer otherwise.

So this type already prevents you from getting the behavior you want.

Thirdly, your issue is with the C and C++ languages which exhibit the behavior to which you take exception.  Given that promotion to `int` is what fundamental integer types do here, it is correct that `type_safe::integer` [also does this](http://foonathan.net/doc/type_safe/doc_integer.html#ts::integer-IntegerT,Policy-):

> It behaves exactly like the built-in types except that narrowing conversions are not allowed.

**Comment by nicola-gigante** [comment]
I agree with @johnmcfarlane here. If the types are intended to safely wrap built-in types, they should mimic built-in types as soon as the operations are safe.

**Comment by damu** [comment]
"Oh you are just stupid" Why do we even need unsigned types? Just get rid of them!
I pointed out a surprising pitfall and you tell me that that surprise stems from my knowledge of C++? How would I be able to point that out if I would not know about the integer promotion rule? Ask developers and let them guess the type and value of my auto variable...

I didn't know that this library marks unsigned overflows as undefined behavior, and I think that that is a really stupid idea. Undefined behavior is bad enough, one doesn't have to add more of that. I had a similar idea to stricter types and did the reverse: my signed integer overflows are actually not undefined behavior to remove that pitfall (I convert them to unsigned and back to achieve that, that should be 0 cost). Ask developers of C/C++ and other languages about how many would expect signed overflows being able to create completely different code if the compiler wants to due to the weirdness of signed overflows being undefined behavior.
Compilers should really have a flag that let's them point out places where they create weird / possibly unintended code due to undefined behavior. That's one of the major issues of C++.
One of my intentions is to make C++ safer. UB and surprising rules are the opposite.

**Comment by foonathan** [comment]
> I didn't know that this library marks unsigned overflows as undefined behavior, and I think that that is a really stupid idea.

To be fair, this is not quite correct: https://github.com/foonathan/type_safe/blob/master/include/type_safe/arithmetic_policy.hpp

You can choose between default, UB or checked. And UB will do assertions in debug mode.

**Comment by Xenoamor** [comment]
Was this deemed to be outside the scope of this project?
I'm not sure the argument, that unsigned values to a larger signed value is unsafe, is a particularly good one as the conversion would only be permitted one way

**Comment by foonathan** [comment]
Hm, I no longer really care strongly about that issue. If you make a PR, I'll merge it.
