### ISSUE TITLE
Add operators -> and * to optional

### ISSUE THREAD

**Issue by ubruhin** [foonathan/type_safe#86]
These operators are very handy to access the contained value of an `optional`, just like [those from `std::optional`](https://en.cppreference.com/w/cpp/utility/optional/operator*).

Or are there arguments against these operators?

**Comment by foonathan** [comment]
Yes, they are convenient, which is why I didn't add them. It should be a deliberete action to access the value as it might be dangerous. Also, I didn't want to make it seem like a pointer.

But now with the experience of actually using it, I might agree. However, I'm definitely not going to add them to type_safe::optional, but maybe to my future vocabulary type library as outlined in #82.
